### ISSUE TITLE
Time not working until date is updated

### ISSUE THREAD

**Issue by dontboyle** [RenovoSolutions/ngx-datetimepicker#111]
Source: demo site: https://renovosolutions.github.io/ngx-datetimepicker/

![image](https://user-images.githubusercontent.com/8333350/107425544-b5cb0100-6ae4-11eb-97d1-15bf90bace97.png)

**Comment by benjamin-a-kuntz** [comment]
Resolved in https://github.com/RenovoSolutions/ngx-datetimepicker/pull/160
