### ISSUE TITLE
`npm test` is broken

### ISSUE THREAD

**Issue by ibedard16** [RenovoSolutions/ngx-datetimepicker#156]
Right now, the test script in `package.json` is `npm test`.

That means that, when I try to run tests, npm just runs the same command a few times until it gets tired. It fortunately doesn't do it forever.

I tried to run tests more directly with `ng test`, and that command was broken too. The tests need to be fixed.

**Comment by benjamin-a-kuntz** [comment]
Resolved in https://github.com/RenovoSolutions/ngx-datetimepicker/pull/157
