### ISSUE TITLE
Time picker is not completely functional

### ISSUE THREAD

**Issue by JoshDSommer** [RenovoSolutions/ngx-datetimepicker#26]
you cannont set a time from the selectedTime input

**Comment by ghost** [comment]
@TheOriginalJosh  I've fixed on my fork copy you can check it. 

Asking the team if I can create PR on the changes I made on my fork copy for this and also works for angular 4

**Comment by JoshDSommer** [comment]
@JojiePalahang that sounds great! thank you. please add your self to the contributor section in the readme as well.
