### ISSUE TITLE
Template files not found

### ISSUE THREAD

**Issue by AndreasGassmann** [RenovoSolutions/ngx-datetimepicker#30]
Hi,

I tried to use your datepicker in an Ionic v2 project, but sadly I couldn't get it to work. I installed it, included it in my app.module.ts and then tried to use the <ngx-datetime-picker>, just like in the demo. However, when I try to load the page, I get the following error:

```
Unhandled Promise rejection: Failed to load time.component.html
Zone: <root> ; Task: Promise.then ; Value: Failed to load time.component.html undefined
Error: Uncaught (in promise): Failed to load time.component.html
GET http://localhost:8100/date.component.html 404 (Not Found)
GET http://localhost:8100/datePicker.component.html 404 (Not Found)
GET http://localhost:8100/datetimepicker.component.html 404 (Not Found)
GET http://localhost:8100/timePicker.component.html 404 (Not Found)
```

Might that be because ionic v2 is still based on ng2?

Thanks for your help!

**Comment by JoshDSommer** [comment]
@AndreasGassmann That's a good question, This is setup with a web browser in mind and and i think in the case of Ionic would probably just fall back to a `<input type="date" />` etc.

**Comment by AndreasGassmann** [comment]
Sorry, I forgot to mention that we are planning to use the app primarily as a webapp. So I was testing it in chrome on my mac.
I also tested your demo on my iPhone and it fell back to the native date input, just like it should.

**Comment by JoshDSommer** [comment]
Cool, it's still very much a work in progress so if you have any issues let us know and or don't hesitate to make a PR.
