### ISSUE TITLE
Allow placeholder for input

### ISSUE THREAD

**Issue by picosam** [RenovoSolutions/ngx-datetimepicker#35]
Can we allow for setting the placeholder value of the input to the date format?

**Comment by JoshDSommer** [comment]
Sure, this would be great., we accept PR's if you want to knock this out. if not I'll get to it sometime this week.

**Comment by JoshDSommer** [comment]
https://github.com/RenovoSolutions/ngx-datetimepicker/pull/36 and will be available in version 1.0.7
