### ISSUE TITLE
datetime doesn't seem to save

### ISSUE THREAD

**Issue by eng17** [RenovoSolutions/ngx-datetimepicker#47]
I'm using a ngx-datetime-picker.  If I select a date/time with the mouse, the input control is populated with the new date/time and the next time the picker opens, it shows the new date/time, as expected.  However, if I manually edit the text input, the new date/time stays in the edit box, but the picker does not reflect the change.    Not sure why.

My code:
  <ngx-datetime-picker [(selectedDateTime)]="myDate" 
(selectedDateTimeChange)="myChange($event)"></ngx-datetime-picker>

**Comment by jrquick17** [comment]
This works fine in the demo [found here](https://github.com/RenovoSolutions/ngx-datetimepicker/tree/master/demo).
