### ISSUE TITLE
.invalid won't clear upon manual edit

### ISSUE THREAD

**Issue by eng17** [RenovoSolutions/ngx-datetimepicker#48]
If you manually remove the last letter (the 'm') making the string invalid, then the .invalid class appears on the div, as expected.  However, picking a valid date/time with the mouse does not clear the .invalid class.  You must manually edit the date, making it valid.  Then onblur removes the .invalid class.  That is the only way to clear the .invalid class.  I believe this is because the newDatePicked function does not clear the this.invalid field.

**Comment by jrquick17** [comment]
@eng17 @JoshDSommer This issue has been fixed in [PR 71](https://github.com/RenovoSolutions/ngx-datetimepicker/pull/71).

**Comment by JoshDSommer** [comment]
@jrquick17 Thank you again! this has been published in 2.3.0 beta-0 closing this issue.
