### ISSUE TITLE
Could you tell me how to set minDate and maxDate on this control?

### ISSUE THREAD

**Issue by pritesh-volansys** [RenovoSolutions/ngx-datetimepicker#54]

**Comment by pritesh-volansys** [comment]
Is there any functionality like we can set minDate and maxDate for datepicker

**Comment by JoshDSommer** [comment]
Hi @pritesh-volansys, there is a `min` and `max` properties exposed  On the DatePicker, However, those properties are not currently on the DateTimePicker and TimePicker.

**Comment by pritesh-volansys** [comment]
Can possible to add min & max properties in DateTimePicker? I need both data and time picker. But min & max value set on the date only. Urgent requirement!
