### ISSUE TITLE
ngx-datetimepicker gets hidden under rows and cells

### ISSUE THREAD

**Issue by Prabhatking** [RenovoSolutions/ngx-datetimepicker#56]
I am implementing ngx-datetime picker in a Grid cell. the calendar is getting hidden inside the cell.
In bootstrap we have something called container ='Body' to solve such problems. 

What CSS settings we can change here to achieve the same.

![image](https://user-images.githubusercontent.com/40017221/41081130-41cc149c-6a47-11e8-89b1-f56c08e529a9.png)

**Comment by jrquick17** [comment]
Try adding position to the element.

For example:

```
ngx-date-picker ngx-date {
  position: absolute;
  top: 40px;
}
```

**Comment by benjamin-a-kuntz** [comment]
No response following jrquick17's comment.
Closing issue.
