### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by sputnikOS** [RenovoSolutions/ngx-datetimepicker#57]
Whenever I access the dropdown timepicker I receive the following error:
`TimePickerComponent.html:1 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'selectedHour: undefined'. Current value: 'selectedHour: 0'.`

I have tried using both `ngModel` and `selectedTime`. Can anyone provide some guidance?

**Comment by vosh4k** [comment]
Did you find a solution? I'm struggling with the same issue. Since you closed this issue yourself I assume that you solved it.
