### ISSUE TITLE
Cannot build with Angular Ivy

### ISSUE THREAD

**Issue by jrquick17** [RenovoSolutions/ngx-datetimepicker#69]
When building with Ivy enabled I get this error `Error: Internal Error: Unexpected interpolation` from this package.

**Comment by JoshDSommer** [comment]
We are going to have to update the build system to use ng-packagr That will be I'm assuming the best way to go about it.

**Comment by jrquick17** [comment]
@JoshDSommer I added `ng-packagr` in [Pull Request #70](https://github.com/RenovoSolutions/ngx-datetimepicker/pull/70).

**Comment by JoshDSommer** [comment]
published in  ngx-datetime-picker@2.3.0-beta.0

**Comment by JoshDSommer** [comment]
I'm going to close this issue for now, thank you for all your hard work @jrquick17 !
