### ISSUE TITLE
Tabbing to the input does not automatically open the popup.

### ISSUE THREAD

**Issue by jrquick17** [RenovoSolutions/ngx-datetimepicker#72]
When using the tab key to switch between form elements the date, datetime,  and time pickers do not automatically open. They only work on click which can be an issue for accessibility.

**Comment by jrquick17** [comment]
@JoshDSommer  This has been fixed in [PR 73](https://github.com/RenovoSolutions/ngx-datetimepicker/pull/73).

**Comment by JoshDSommer** [comment]
@jrquick17 I've published pr #73  in ngx-datetime-picker@2.3.0-beta.0, Thank you for everything you've done 🎉 figured with the ng packagr changes it would be good to test that out before hand.
