### ISSUE TITLE
Cannot make a 'prod' build

### ISSUE THREAD

**Issue by achieverprince** [RenovoSolutions/ngx-datetimepicker#76]
```
ERROR in node_modules/ngx-datetime-picker/dateTimePicker.component/dateTimePicker.component.html(4,16): Property 'style' does not exist on type 'DateTimePickerComponent'. Did you mean 's
tyles'?
```

**Use command to reproduce this:**
`ng build --prod`

**Tested in:**
Angular ^8.2.3

**Comment by achieverprince** [comment]
![image](https://user-images.githubusercontent.com/881066/67281642-865a4480-f4ed-11e9-844d-f0fb3f3917f0.png)

I believe this should be "**styles**"

**Comment by achieverprince** [comment]
I can see it is already fixed in commit and latest branch has the fix, but can you please release it and close this issue.
https://github.com/RenovoSolutions/ngx-datetimepicker/commit/9c5d5f2df6e560aec034c2e94f46c8f7f6df9c0b#diff-1380f2f15575c8fae3f3df1fee4d52f8

**Comment by JoshDSommer** [comment]
I've moved 2.3.0 from beta to prod.

**Comment by achieverprince** [comment]
Thanks for the quick release.
