### ISSUE TITLE
Import Error For Latest Version 2.3.0

### ISSUE THREAD

**Issue by bengchet** [RenovoSolutions/ngx-datetimepicker#77]
Hi,

I tried importing latest version 2.3.0 but error below shows
`error TS2305: Module '"../../../../node_modules/ngx-datetime-picker/ngx-datetime-picker"' has no exported member 'DateTimePickerModule'.`

I also checked `ngx-datetime-picker.d.ts` file in `node_modules` and found it exports from main.d.ts which exports nothing.
`export {}`

When I revert back to version 2.1.3, this issue is gone.

Please take a look. Thanks.

**Comment by jrquick17** [comment]
This is fixed in [Pull Request 78](https://github.com/RenovoSolutions/ngx-datetimepicker/pull/78)

**Comment by JoshDSommer** [comment]
3.0.0
