### ISSUE TITLE
Repeatively toggling AM and PM on time picker causes time to change incorrectly

### ISSUE THREAD

**Issue by jrquick17** [RenovoSolutions/ngx-datetimepicker#84]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/7435558/68228387-f7ecc500-ffba-11e9-87f6-7456867c0652.gif)

**Comment by jrquick17** [comment]
This is fixed in [Pull Request 87](https://github.com/RenovoSolutions/ngx-datetimepicker/pull/87)

**Comment by JoshDSommer** [comment]
bug fix is in 3.0.0 release
