### ISSUE TITLE
AM/PM is incorrect between picker and popup

### ISSUE THREAD

**Issue by jrquick17** [RenovoSolutions/ngx-datetimepicker#85]
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/7435558/68230981-c6c2c380-ffbf-11e9-9412-1f321a15ea85.gif)

**Comment by jrquick17** [comment]
This is fixed in [Pull Request 87](https://github.com/RenovoSolutions/ngx-datetimepicker/pull/87)

**Comment by JoshDSommer** [comment]
3.0.0
