### ISSUE TITLE
[Feature]: Upgrade to support Angular 9

### ISSUE THREAD

**Issue by jrquick17** [RenovoSolutions/ngx-datetimepicker#90]
`ERROR in Internal Error: Unexpected interpolation`

With Angular 9, I am getting the error while build.
I use ngx-datetime-picker@2.1.3

Could you please help me?

_Originally posted by @lastch in https://github.com/RenovoSolutions/ngx-datetimepicker/issues/88#issuecomment-585848946_

**Comment by dineshmaths1** [comment]
use     "ngx-datetime-picker": "^3.0.0"
