### ISSUE TITLE
[Feature] Export DateComponent and TimeComponent in DateTimePickerModule 

### ISSUE THREAD

**Issue by Totati** [RenovoSolutions/ngx-datetimepicker#91]
Hi, we would like to use your inner `DateComponent` and `TimeComponent` components to create a customized `DateTimePickerComponent`, but they are not reachable outside of your module. Could you export them so we can wrap them in our own date time picker please?

**Comment by benjamin-a-kuntz** [comment]
Resolved in https://github.com/RenovoSolutions/ngx-datetimepicker/pull/92
