### ISSUE TITLE
[Bug]: Hour format changes to 24HR when changing the hours option directly

### ISSUE THREAD

**Issue by jrquick17** [RenovoSolutions/ngx-datetimepicker#93]
I attached a video to show the issue only occurs when changing the hour directly and using non 24 hour format.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/7435558/76013487-8f1c4780-5edd-11ea-89b2-3fc1f3c65b24.gif)

**Comment by dineshmaths1** [comment]
can u pleas tell me how to set min date ?

**Comment by benjamin-a-kuntz** [comment]
Resolved in https://github.com/RenovoSolutions/ngx-datetimepicker/pull/94
