### ISSUE TITLE
calendar button click event is not working ?

### ISSUE THREAD

**Issue by dineshmaths1** [RenovoSolutions/ngx-datetimepicker#98]
Angular 9  If you click calendar button calendar is not appearing ?
`  <ngx-datetime-picker  [min]="min" formControlName="startTime"></ngx-datetime-picker>`
How to fix?

**Comment by benjamin-a-kuntz** [comment]
Project now officially supports only Angular 12 - this does not appear to be a problem in this version.
![image](https://user-images.githubusercontent.com/98501411/159960775-64f9b526-13a6-4e49-aa02-ee8d208e94c1.png)
